### PR TITLE
Port to Python 3 and Django 2.1

### PR DESCRIPTION
**Pull request by zimbrul-co**
Dear Sir/Madam,

This Django driver has not been updated in a while, and now Django has advanced to version 2.1. Python 2 is getting older and older and version 3 is more used now, in my opinion. I need this Django driver for my websites, so I can use CUBRID as a DBMS.

There are all sorts of fixes, Python 3 related fixes, new Django methods that needed to be implemented, and some other improvements.

I have only done basic tests with my Django projects, and fixed whatever errors occurred, and I will do more testing while developing the websites.

Please analyze and review,
Yours sincerely,
Casian Andrei
Zimbrul Comert Online SRL

### CODE REVIEW

**Comment by beyondykk9** [comment]
We'll review the changes. And after testing, the changes will be merged.

**Comment by kisoo-han** [comment]
Casian,

Thank you for your interest on CUBRID and your contribution.
We are on the way of reviewing your codes and it may take couple of weeks. By the way, we need CUBRID Contributor Agreement (CCA) signed by you before we proceed merge process of your code into CUBBRID. This is conventional process and part of our developments and maintenance principals. Please refer following Link [CCA]: https://github.com/CUBRID/cubrid/wiki/CUBRID-Contributor's-Agreement and if you agree on it, please send signed copy to legal@cubrid.org.

Thank you again for your contribution!!

**Comment by beyondykk9** [comment]
Casian,

In the change "Implement case-insensitive lookups using UPPER", the UPPER function should be applied left and right side of the expression. By the way it can be used for case insensitive compare expressions, so we merge the changes.

Thank you for your contribution.

**Comment by zimbrul-co** [comment]
I have signed the CCA and sent to legal@cubrid.org. I apologize for the delay, I was caught up with other matters.

**Comment by beyondykk9** [comment]
@zimbrul-co 

I reverted the changes which you have committed while reviewing the merge version.
Please Request PR again and I will merge the changes.

**Comment by kisoo-han** [comment]
@zimbrul-co 

As @byungwook-kim wrote in previous comment, there is some confusion of processing your contribution to CUBRID-python. 

We carefully reviewed your contribution to CUBRID-python and decided to accept your contribution.

However, @byungwook-kim merged & reverted your pull request. As a result, your contribution is not merged into CUBRID-python at the moment.

We have two possible options to correct this process:

1. You request same PR again, and we merge it.
2. We revert, reverted PR(#6) again by ourselves, it will merge your previous PR into CUBRID-python.

I want to know your opinion on it.

We apologize for inconvenience & thank you for your contribution.

**Comment by zimbrul-co** [comment]
Dear @kisoo-han and @byungwook-kim

I think the best is that you revert the revert - option 2. We don't need another pull request.

I much thank you for the review and for deciding to accept my contribution!

**Pull request merged**
